FROM balenalib/%%BALENA_MACHINE_NAME%%-node:12-stretch-build AS build

WORKDIR /kern-communications
COPY package.json yarn.lock ./
RUN yarn install --pure-lockfile

FROM balenalib/%%BALENA_MACHINE_NAME%%-node:12-stretch-run

WORKDIR /kern-communications
COPY tsconfig.json package.json ./
COPY --from=build /kern-communications/node_modules ./node_modules
COPY src ./src

CMD ["sleep","2h"]
